---
title: "HW4"
author: "Maggie Trout"
date: "2025-02-05"
output: rmdformats::material
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

First:
```{r}
x <- 1.1
a <- 2.2
b <- 3.3
```
For a:
```{r}
z <- x^(a^b)
print(z)
```

For b:
```{r}
z <- ((x^a)^b)
print(z)
```

For c:

```{r}
z <-3*(x^3)+2*(x^2)+1
print(z)
```

# Problem 2

For a:
```{r}
vector_a <- c(1:8, 7:1)
print(vector_a)
```

For b:
```{r}
vector_b1 <- 1:5
vector_b2 <- rep(x=vector_b1,times=vector_b1)
print(vector_b2)
```
OR:
```{r}
vector_b2 <- rep(x=1:5,times=1:5)
print(vector_b2)
```
For c:
```{r}
vector_c3 <- rep(x=5:1,times=1:5)
print(vector_c3)
```
# Problem 3
```{r}
vectorr <- runif(2)
names(vectorr) <- c("x","y")
print(vectorr)
r <- ((vectorr[["x"]]^2) + (vectorr[["y"]]^2))^(1/2)
print(r)
theta <- atan(vectorr[["y"]]/vectorr[["x"]])
print(theta)
```

# Problem 4

a.
```{r}
queue <- c("sheep", "fox", "owl", "ant")
queue <- c(queue,"snake")  
print(queue)
```

b.
```{r}
queue <- queue[queue!="sheep"]
print(queue)
```

c.
```{r}
queue <- c("donkey", queue)
print(queue)
```

d.
```{r}
queue <- queue[queue!="snake"]
print(queue)
```
e.
```{r}
queue <- queue[queue!="owl"]
print(queue) 
```
f.
```{r}
queue <- c(queue[queue!="ant"],"aphid","ant")
print(queue)
```
I do recognize that I can only do it this exact way because I know the ant is already last


g.
```{r}
which(queue=="aphid")
```

# Problem 5
```{r}
vec_1 <- 1:100
vec_2 <- vec_1[(vec_1%%2)!=0&(vec_1%%3)!=0&(vec_1%%7)!=0]
print(vec_2)
```
